services:
  mongodb-interactions:
    image: mongo:latest
    container_name: mongodb-interactions
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
    - "27019:27017"